### ISSUE TITLE
Error: g_sessionID was not found

### ISSUE THREAD

**Issue by HellmannM** [ge-ku/Ban-Checker-for-Steam#39]
When I set my custom API Key in the settings I get this error message under the buttons to scan:
`Error: g_sessionID was not found`
When using the default API Key the "Load whole match history" does nothing and clicking on "Check loaded matches for bans" gives:
`Loaded unchecked matches contain 0 players.`
`We can scan 100 players at a time so we're sending 0 request.`
`0 successful requests so far...`

I tried with both Firefox and Chrome.
Any ideas? Thanks!

**Comment by Obihoernchen** [comment]
same here

**Comment by seriiix** [comment]
same error

**Comment by Ephaltes** [comment]
#40  should fix this problem, once it is approved

**Comment by ajgrinds** [comment]
> #40 should fix this problem, once it is approved

still didnt fix it for me. do I have to update the extension somehow?

note: installed it around 15 minutes ago

**Comment by ge-ku** [comment]
I just included the fix (thanks @Ephaltes!) and uploaded new version to all stores, it can take some time until they are published because of review process, it's already available for Firefox, not yet for Chrome and Edge.

New version number is 1.2.4, tell me if it doesn't work after updating (it should update automatically).

**Comment by ajgrinds** [comment]
> I just included the fix (thanks @Ephaltes!) and uploaded new version to all stores, it can take some time until they are published because of review process, it's already available for Firefox, not yet for Chrome and Edge.
> 
> New version number is 1.2.4, tell me if it doesn't work after updating (it should update automatically).

still no update from google

**Comment by ge-ku** [comment]
It's up on Chrome and Edge store now, if it doesn't work make sure your version is 1.2.4, let me know if it doesn't work after updating. Works fine for me.

**Comment by HellmannM** [comment]
Tested on Firefox and my issue is fixed! Thank you very much!!
